[package]
name = "analog-sdk-macro"
version = "1.9.0"
description = "Analog SDK Macro"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
repository = "https://github.com/analog-labs/analog"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-sdk-macro"
license = "Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
bs58 = "0.4.0"
proc-macro2 = "1.0.19"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }
rustversion = "1.0.3"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
