[package]
name = "analog-version"
version = "1.9.0"
description = "Analog Version"
authors = ["Analog Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/analog-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/analog-version"
edition = "2018"

[dependencies]
log = "0.4.14"
serde = "1.0.130"
serde_derive = "1.0.103"
analog-frozen-abi = { path = "../frozen-abi", version = "=1.9.0" }
analog-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.9.0" }
analog-sdk = { path = "../sdk", version = "=1.9.0" }

[lib]
name = "analog_version"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
