[package]
name = "analog-transaction-status"
version = "1.9.0"
description = "Analog transaction status types"
authors = ["Analog Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/analog-labs/solana"
homepage = "https://solana.com/"
documentation = "https://docs.rs/analog-transaction-status"
license = "Apache-2.0"
edition = "2018"

[dependencies]
base64 = "0.12.3"
bincode = "1.3.3"
bs58 = "0.4.0"
Inflector = "0.11.4"
lazy_static = "1.4.0"
log = "0.4.14"
serde = "1.0.130"
serde_derive = "1.0.103"
serde_json = "1.0.69"
analog-account-decoder = { path = "../account-decoder", version = "=1.9.0" }
analog-measure = { path = "../measure", version = "=1.9.0" }
analog-metrics = { path = "../metrics", version = "=1.9.0" }
analog-runtime = { path = "../runtime", version = "=1.9.0" }
analog-sdk = { path = "../sdk", version = "=1.9.0" }
analog-vote-program = { path = "../programs/vote", version = "=1.9.0" }
spl-associated-token-account-v1-0 = { package = "spl-associated-token-account", version = "=1.0.3", features = ["no-entrypoint"] }
spl-memo = { version = "=3.0.1", features = ["no-entrypoint"] }
spl-token-v2-0 = { package = "spl-token", version = "=3.2.0", features = ["no-entrypoint"] }
thiserror = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
