[package]
name = "analog-frozen-abi-macro"
version = "1.9.0"
description = "Analog Frozen ABI Macro"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
repository = "https://github.com/analog-labs/analog"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-frozen-abi-macro"
license = "Apache-2.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }

[build-dependencies]
rustc_version = "0.4"
