[package]
name = "analog-send-transaction-service"
version = "1.9.0"
description = "Analog send transaction service"
authors = ["Analog Maintainers <maintainers@analog.foundation>"]
repository = "https://github.com/analog-labs/analog"
homepage = "https://analog.com/"
documentation = "https://docs.rs/analog-send-transaction-service"
license = "Apache-2.0"
edition = "2018"

[dependencies]
log = "0.4.14"
analog-logger = { path = "../logger", version = "=1.9.0" }
analog-metrics = { path = "../metrics", version = "=1.9.0" }
analog-runtime = { path = "../runtime", version = "=1.9.0" }
analog-sdk = { path = "../sdk", version = "=1.9.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
